source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CCImageBrowser_Example', :exclusive => true do
  pod "CCImageBrowser", :path => "../"
end

target 'CCImageBrowser_Tests', :exclusive => true do
  pod "CCImageBrowser", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
